package com.gj.administrator.gjerp.domain;

import com.gj.administrator.gjerp.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.gj.administrator.gjerp.dao.EmployeeDao;
import com.gj.administrator.gjerp.dao.ScheduleDao;
import com.gj.administrator.gjerp.dao.TaskDao;
import com.gj.administrator.gjerp.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "EMPLOYEE".
 */
public class Employee {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String employee_type;
    /** Not-null value. */
    private String telphone;
    /** Not-null value. */
    private String email;
    /** Not-null value. */
    private java.util.Date create_time;
    /** Not-null value. */
    private String gender;
    private Long user_id;
    private Long task_id;
    private Long schedule_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient EmployeeDao myDao;

    private User user;
    private Long user__resolvedKey;

    private Task task;
    private Long task__resolvedKey;

    private Schedule schedule;
    private Long schedule__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Employee() {
    }

    public Employee(Long id) {
        this.id = id;
    }

    public Employee(Long id, String name, String employee_type, String telphone, String email, java.util.Date create_time, String gender, Long user_id, Long task_id, Long schedule_id) {
        this.id = id;
        this.name = name;
        this.employee_type = employee_type;
        this.telphone = telphone;
        this.email = email;
        this.create_time = create_time;
        this.gender = gender;
        this.user_id = user_id;
        this.task_id = task_id;
        this.schedule_id = schedule_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getEmployeeDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getEmployee_type() {
        return employee_type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmployee_type(String employee_type) {
        this.employee_type = employee_type;
    }

    /** Not-null value. */
    public String getTelphone() {
        return telphone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /** Not-null value. */
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }

    /** Not-null value. */
    public java.util.Date getCreate_time() {
        return create_time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreate_time(java.util.Date create_time) {
        this.create_time = create_time;
    }

    /** Not-null value. */
    public String getGender() {
        return gender;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGender(String gender) {
        this.gender = gender;
    }

    public Long getUser_id() {
        return user_id;
    }

    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    public Long getTask_id() {
        return task_id;
    }

    public void setTask_id(Long task_id) {
        this.task_id = task_id;
    }

    public Long getSchedule_id() {
        return schedule_id;
    }

    public void setSchedule_id(Long schedule_id) {
        this.schedule_id = schedule_id;
    }

    /** To-one relationship, resolved on first access. */
    public User getUser() {
        Long __key = this.user_id;
        if (user__resolvedKey == null || !user__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UserDao targetDao = daoSession.getUserDao();
            User userNew = targetDao.load(__key);
            synchronized (this) {
                user = userNew;
            	user__resolvedKey = __key;
            }
        }
        return user;
    }

    public void setUser(User user) {
        synchronized (this) {
            this.user = user;
            user_id = user == null ? null : user.getId();
            user__resolvedKey = user_id;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Task getTask() {
        Long __key = this.task_id;
        if (task__resolvedKey == null || !task__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TaskDao targetDao = daoSession.getTaskDao();
            Task taskNew = targetDao.load(__key);
            synchronized (this) {
                task = taskNew;
            	task__resolvedKey = __key;
            }
        }
        return task;
    }

    public void setTask(Task task) {
        synchronized (this) {
            this.task = task;
            task_id = task == null ? null : task.getId();
            task__resolvedKey = task_id;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Schedule getSchedule() {
        Long __key = this.schedule_id;
        if (schedule__resolvedKey == null || !schedule__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ScheduleDao targetDao = daoSession.getScheduleDao();
            Schedule scheduleNew = targetDao.load(__key);
            synchronized (this) {
                schedule = scheduleNew;
            	schedule__resolvedKey = __key;
            }
        }
        return schedule;
    }

    public void setSchedule(Schedule schedule) {
        synchronized (this) {
            this.schedule = schedule;
            schedule_id = schedule == null ? null : schedule.getId();
            schedule__resolvedKey = schedule_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
