package com.gj.administrator.gjerp.domain;

import com.gj.administrator.gjerp.dao.DaoSession;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoException;

import com.gj.administrator.gjerp.dao.GuestDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "GUEST".
 */
public class Guest {

    private Long id;
    /** Not-null value. */
    private String name;
    private int guest_type;
    /** Not-null value. */
    private String gender;
    /** Not-null value. */
    private String card_type;
    /** Not-null value. */
    private String card_id;
    /** Not-null value. */
    private String telphone;
    /** Not-null value. */
    private java.util.Date create_time;
    private String country;
    private String address;
    private String zip;
    private String email;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient GuestDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Guest() {
    }

    public Guest(Long id) {
        this.id = id;
    }

    public Guest(Long id, String name, int guest_type, String gender, String card_type, String card_id, String telphone, java.util.Date create_time, String country, String address, String zip, String email) {
        this.id = id;
        this.name = name;
        this.guest_type = guest_type;
        this.gender = gender;
        this.card_type = card_type;
        this.card_id = card_id;
        this.telphone = telphone;
        this.create_time = create_time;
        this.country = country;
        this.address = address;
        this.zip = zip;
        this.email = email;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getGuestDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getGuest_type() {
        return guest_type;
    }

    public void setGuest_type(int guest_type) {
        this.guest_type = guest_type;
    }

    /** Not-null value. */
    public String getGender() {
        return gender;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /** Not-null value. */
    public String getCard_type() {
        return card_type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCard_type(String card_type) {
        this.card_type = card_type;
    }

    /** Not-null value. */
    public String getCard_id() {
        return card_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCard_id(String card_id) {
        this.card_id = card_id;
    }

    /** Not-null value. */
    public String getTelphone() {
        return telphone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /** Not-null value. */
    public java.util.Date getCreate_time() {
        return create_time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreate_time(java.util.Date create_time) {
        this.create_time = create_time;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
