package com.gj.administrator.gjerp.domain;

import com.gj.administrator.gjerp.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.gj.administrator.gjerp.dao.PartnerDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PARTNER".
 */
public class Partner {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String partner_type;
    /** Not-null value. */
    private String telphone;
    /** Not-null value. */
    private String email;
    /** Not-null value. */
    private java.util.Date create_time;
    /** Not-null value. */
    private String company;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient PartnerDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Partner() {
    }

    public Partner(Long id) {
        this.id = id;
    }

    public Partner(Long id, String name, String partner_type, String telphone, String email, java.util.Date create_time, String company) {
        this.id = id;
        this.name = name;
        this.partner_type = partner_type;
        this.telphone = telphone;
        this.email = email;
        this.create_time = create_time;
        this.company = company;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getPartnerDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getPartner_type() {
        return partner_type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPartner_type(String partner_type) {
        this.partner_type = partner_type;
    }

    /** Not-null value. */
    public String getTelphone() {
        return telphone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /** Not-null value. */
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }

    /** Not-null value. */
    public java.util.Date getCreate_time() {
        return create_time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreate_time(java.util.Date create_time) {
        this.create_time = create_time;
    }

    /** Not-null value. */
    public String getCompany() {
        return company;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompany(String company) {
        this.company = company;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
