package com.gj.administrator.gjerp.domain;

import com.gj.administrator.gjerp.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.gj.administrator.gjerp.dao.RoomTypeDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ROOM_TYPE".
 */
public class RoomType {

    private Long id;
    /** Not-null value. */
    private String type_name;
    private double price;
    /** Not-null value. */
    private String price_unit;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient RoomTypeDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public RoomType() {
    }

    public RoomType(Long id) {
        this.id = id;
    }

    public RoomType(Long id, String type_name, double price, String price_unit) {
        this.id = id;
        this.type_name = type_name;
        this.price = price;
        this.price_unit = price_unit;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getRoomTypeDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getType_name() {
        return type_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType_name(String type_name) {
        this.type_name = type_name;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    /** Not-null value. */
    public String getPrice_unit() {
        return price_unit;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPrice_unit(String price_unit) {
        this.price_unit = price_unit;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
