package com.gj.administrator.gjerp.domain;

import com.gj.administrator.gjerp.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.gj.administrator.gjerp.dao.DialogDao;
import com.gj.administrator.gjerp.dao.HotelDao;
import com.gj.administrator.gjerp.dao.StaffDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "STAFF".
 */
public class Staff {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String gender;
    /** Not-null value. */
    private String rank;
    /** Not-null value. */
    private String positon;
    private long hotel_id;
    private Long dialog_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient StaffDao myDao;

    private Hotel hotel;
    private Long hotel__resolvedKey;

    private Dialog dialog;
    private Long dialog__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Staff() {
    }

    public Staff(Long id) {
        this.id = id;
    }

    public Staff(Long id, String name, String gender, String rank, String positon, long hotel_id, Long dialog_id) {
        this.id = id;
        this.name = name;
        this.gender = gender;
        this.rank = rank;
        this.positon = positon;
        this.hotel_id = hotel_id;
        this.dialog_id = dialog_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getStaffDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getGender() {
        return gender;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /** Not-null value. */
    public String getRank() {
        return rank;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRank(String rank) {
        this.rank = rank;
    }

    /** Not-null value. */
    public String getPositon() {
        return positon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPositon(String positon) {
        this.positon = positon;
    }

    public long getHotel_id() {
        return hotel_id;
    }

    public void setHotel_id(long hotel_id) {
        this.hotel_id = hotel_id;
    }

    public Long getDialog_id() {
        return dialog_id;
    }

    public void setDialog_id(Long dialog_id) {
        this.dialog_id = dialog_id;
    }

    /** To-one relationship, resolved on first access. */
    public Hotel getHotel() {
        long __key = this.hotel_id;
        if (hotel__resolvedKey == null || !hotel__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            HotelDao targetDao = daoSession.getHotelDao();
            Hotel hotelNew = targetDao.load(__key);
            synchronized (this) {
                hotel = hotelNew;
            	hotel__resolvedKey = __key;
            }
        }
        return hotel;
    }

    public void setHotel(Hotel hotel) {
        if (hotel == null) {
            throw new DaoException("To-one property 'hotel_id' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.hotel = hotel;
            hotel_id = hotel.getId();
            hotel__resolvedKey = hotel_id;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Dialog getDialog() {
        Long __key = this.dialog_id;
        if (dialog__resolvedKey == null || !dialog__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DialogDao targetDao = daoSession.getDialogDao();
            Dialog dialogNew = targetDao.load(__key);
            synchronized (this) {
                dialog = dialogNew;
            	dialog__resolvedKey = __key;
            }
        }
        return dialog;
    }

    public void setDialog(Dialog dialog) {
        synchronized (this) {
            this.dialog = dialog;
            dialog_id = dialog == null ? null : dialog.getId();
            dialog__resolvedKey = dialog_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
