package com.gj.administrator.gjerp.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.gj.administrator.gjerp.domain.Guest;
import com.gj.administrator.gjerp.domain.Room;

import com.gj.administrator.gjerp.domain.BookRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK_RECORD".
*/
public class BookRecordDao extends AbstractDao<BookRecord, Long> {

    public static final String TABLENAME = "BOOK_RECORD";

    /**
     * Properties of entity BookRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Create_date = new Property(1, java.util.Date.class, "create_date", false, "CREATE_DATE");
        public final static Property Arrive_date = new Property(2, java.util.Date.class, "arrive_date", false, "ARRIVE_DATE");
        public final static Property Leave_date = new Property(3, java.util.Date.class, "leave_date", false, "LEAVE_DATE");
        public final static Property Deposit = new Property(4, Double.class, "deposit", false, "DEPOSIT");
        public final static Property Book_day = new Property(5, Integer.class, "book_day", false, "BOOK_DAY");
        public final static Property Guest_id = new Property(6, long.class, "guest_id", false, "GUEST_ID");
        public final static Property Room_id = new Property(7, long.class, "room_id", false, "ROOM_ID");
    };

    private DaoSession daoSession;


    public BookRecordDao(DaoConfig config) {
        super(config);
    }
    
    public BookRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CREATE_DATE\" INTEGER NOT NULL ," + // 1: create_date
                "\"ARRIVE_DATE\" INTEGER," + // 2: arrive_date
                "\"LEAVE_DATE\" INTEGER," + // 3: leave_date
                "\"DEPOSIT\" REAL," + // 4: deposit
                "\"BOOK_DAY\" INTEGER," + // 5: book_day
                "\"GUEST_ID\" INTEGER NOT NULL ," + // 6: guest_id
                "\"ROOM_ID\" INTEGER NOT NULL );"); // 7: room_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK_RECORD\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BookRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCreate_date().getTime());
 
        java.util.Date arrive_date = entity.getArrive_date();
        if (arrive_date != null) {
            stmt.bindLong(3, arrive_date.getTime());
        }
 
        java.util.Date leave_date = entity.getLeave_date();
        if (leave_date != null) {
            stmt.bindLong(4, leave_date.getTime());
        }
 
        Double deposit = entity.getDeposit();
        if (deposit != null) {
            stmt.bindDouble(5, deposit);
        }
 
        Integer book_day = entity.getBook_day();
        if (book_day != null) {
            stmt.bindLong(6, book_day);
        }
        stmt.bindLong(7, entity.getGuest_id());
        stmt.bindLong(8, entity.getRoom_id());
    }

    @Override
    protected void attachEntity(BookRecord entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BookRecord readEntity(Cursor cursor, int offset) {
        BookRecord entity = new BookRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            new java.util.Date(cursor.getLong(offset + 1)), // create_date
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // arrive_date
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // leave_date
            cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4), // deposit
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // book_day
            cursor.getLong(offset + 6), // guest_id
            cursor.getLong(offset + 7) // room_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BookRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCreate_date(new java.util.Date(cursor.getLong(offset + 1)));
        entity.setArrive_date(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setLeave_date(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setDeposit(cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4));
        entity.setBook_day(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setGuest_id(cursor.getLong(offset + 6));
        entity.setRoom_id(cursor.getLong(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BookRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BookRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getGuestDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getRoomDao().getAllColumns());
            builder.append(" FROM BOOK_RECORD T");
            builder.append(" LEFT JOIN GUEST T0 ON T.\"GUEST_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN ROOM T1 ON T.\"ROOM_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected BookRecord loadCurrentDeep(Cursor cursor, boolean lock) {
        BookRecord entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Guest guest = loadCurrentOther(daoSession.getGuestDao(), cursor, offset);
         if(guest != null) {
            entity.setGuest(guest);
        }
        offset += daoSession.getGuestDao().getAllColumns().length;

        Room room = loadCurrentOther(daoSession.getRoomDao(), cursor, offset);
         if(room != null) {
            entity.setRoom(room);
        }

        return entity;    
    }

    public BookRecord loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<BookRecord> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<BookRecord> list = new ArrayList<BookRecord>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<BookRecord> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<BookRecord> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
