package com.gj.administrator.gjerp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.gj.administrator.gjerp.domain.Hotel;
import com.gj.administrator.gjerp.domain.Guest;
import com.gj.administrator.gjerp.domain.Room;

import com.gj.administrator.gjerp.dao.HotelDao;
import com.gj.administrator.gjerp.dao.GuestDao;
import com.gj.administrator.gjerp.dao.RoomDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hotelDaoConfig;
    private final DaoConfig guestDaoConfig;
    private final DaoConfig roomDaoConfig;

    private final HotelDao hotelDao;
    private final GuestDao guestDao;
    private final RoomDao roomDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hotelDaoConfig = daoConfigMap.get(HotelDao.class).clone();
        hotelDaoConfig.initIdentityScope(type);

        guestDaoConfig = daoConfigMap.get(GuestDao.class).clone();
        guestDaoConfig.initIdentityScope(type);

        roomDaoConfig = daoConfigMap.get(RoomDao.class).clone();
        roomDaoConfig.initIdentityScope(type);

        hotelDao = new HotelDao(hotelDaoConfig, this);
        guestDao = new GuestDao(guestDaoConfig, this);
        roomDao = new RoomDao(roomDaoConfig, this);

        registerDao(Hotel.class, hotelDao);
        registerDao(Guest.class, guestDao);
        registerDao(Room.class, roomDao);
    }
    
    public void clear() {
        hotelDaoConfig.getIdentityScope().clear();
        guestDaoConfig.getIdentityScope().clear();
        roomDaoConfig.getIdentityScope().clear();
    }

    public HotelDao getHotelDao() {
        return hotelDao;
    }

    public GuestDao getGuestDao() {
        return guestDao;
    }

    public RoomDao getRoomDao() {
        return roomDao;
    }

}
