package com.gj.administrator.gjerp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.gj.administrator.gjerp.domain.Hotel;
import com.gj.administrator.gjerp.domain.RoomType;
import com.gj.administrator.gjerp.domain.Room;
import com.gj.administrator.gjerp.domain.User;
import com.gj.administrator.gjerp.domain.Schedule;
import com.gj.administrator.gjerp.domain.Task;
import com.gj.administrator.gjerp.domain.Employee;
import com.gj.administrator.gjerp.domain.Guest;
import com.gj.administrator.gjerp.domain.Partner;
import com.gj.administrator.gjerp.domain.Supplier;
import com.gj.administrator.gjerp.domain.Dialog;
import com.gj.administrator.gjerp.domain.Message;
import com.gj.administrator.gjerp.domain.BookRecord;
import com.gj.administrator.gjerp.domain.OutRecord;

import com.gj.administrator.gjerp.dao.HotelDao;
import com.gj.administrator.gjerp.dao.RoomTypeDao;
import com.gj.administrator.gjerp.dao.RoomDao;
import com.gj.administrator.gjerp.dao.UserDao;
import com.gj.administrator.gjerp.dao.ScheduleDao;
import com.gj.administrator.gjerp.dao.TaskDao;
import com.gj.administrator.gjerp.dao.EmployeeDao;
import com.gj.administrator.gjerp.dao.GuestDao;
import com.gj.administrator.gjerp.dao.PartnerDao;
import com.gj.administrator.gjerp.dao.SupplierDao;
import com.gj.administrator.gjerp.dao.DialogDao;
import com.gj.administrator.gjerp.dao.MessageDao;
import com.gj.administrator.gjerp.dao.BookRecordDao;
import com.gj.administrator.gjerp.dao.OutRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hotelDaoConfig;
    private final DaoConfig roomTypeDaoConfig;
    private final DaoConfig roomDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig scheduleDaoConfig;
    private final DaoConfig taskDaoConfig;
    private final DaoConfig employeeDaoConfig;
    private final DaoConfig guestDaoConfig;
    private final DaoConfig partnerDaoConfig;
    private final DaoConfig supplierDaoConfig;
    private final DaoConfig dialogDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig bookRecordDaoConfig;
    private final DaoConfig outRecordDaoConfig;

    private final HotelDao hotelDao;
    private final RoomTypeDao roomTypeDao;
    private final RoomDao roomDao;
    private final UserDao userDao;
    private final ScheduleDao scheduleDao;
    private final TaskDao taskDao;
    private final EmployeeDao employeeDao;
    private final GuestDao guestDao;
    private final PartnerDao partnerDao;
    private final SupplierDao supplierDao;
    private final DialogDao dialogDao;
    private final MessageDao messageDao;
    private final BookRecordDao bookRecordDao;
    private final OutRecordDao outRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hotelDaoConfig = daoConfigMap.get(HotelDao.class).clone();
        hotelDaoConfig.initIdentityScope(type);

        roomTypeDaoConfig = daoConfigMap.get(RoomTypeDao.class).clone();
        roomTypeDaoConfig.initIdentityScope(type);

        roomDaoConfig = daoConfigMap.get(RoomDao.class).clone();
        roomDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        scheduleDaoConfig = daoConfigMap.get(ScheduleDao.class).clone();
        scheduleDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        employeeDaoConfig = daoConfigMap.get(EmployeeDao.class).clone();
        employeeDaoConfig.initIdentityScope(type);

        guestDaoConfig = daoConfigMap.get(GuestDao.class).clone();
        guestDaoConfig.initIdentityScope(type);

        partnerDaoConfig = daoConfigMap.get(PartnerDao.class).clone();
        partnerDaoConfig.initIdentityScope(type);

        supplierDaoConfig = daoConfigMap.get(SupplierDao.class).clone();
        supplierDaoConfig.initIdentityScope(type);

        dialogDaoConfig = daoConfigMap.get(DialogDao.class).clone();
        dialogDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        bookRecordDaoConfig = daoConfigMap.get(BookRecordDao.class).clone();
        bookRecordDaoConfig.initIdentityScope(type);

        outRecordDaoConfig = daoConfigMap.get(OutRecordDao.class).clone();
        outRecordDaoConfig.initIdentityScope(type);

        hotelDao = new HotelDao(hotelDaoConfig, this);
        roomTypeDao = new RoomTypeDao(roomTypeDaoConfig, this);
        roomDao = new RoomDao(roomDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        scheduleDao = new ScheduleDao(scheduleDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);
        employeeDao = new EmployeeDao(employeeDaoConfig, this);
        guestDao = new GuestDao(guestDaoConfig, this);
        partnerDao = new PartnerDao(partnerDaoConfig, this);
        supplierDao = new SupplierDao(supplierDaoConfig, this);
        dialogDao = new DialogDao(dialogDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        bookRecordDao = new BookRecordDao(bookRecordDaoConfig, this);
        outRecordDao = new OutRecordDao(outRecordDaoConfig, this);

        registerDao(Hotel.class, hotelDao);
        registerDao(RoomType.class, roomTypeDao);
        registerDao(Room.class, roomDao);
        registerDao(User.class, userDao);
        registerDao(Schedule.class, scheduleDao);
        registerDao(Task.class, taskDao);
        registerDao(Employee.class, employeeDao);
        registerDao(Guest.class, guestDao);
        registerDao(Partner.class, partnerDao);
        registerDao(Supplier.class, supplierDao);
        registerDao(Dialog.class, dialogDao);
        registerDao(Message.class, messageDao);
        registerDao(BookRecord.class, bookRecordDao);
        registerDao(OutRecord.class, outRecordDao);
    }
    
    public void clear() {
        hotelDaoConfig.getIdentityScope().clear();
        roomTypeDaoConfig.getIdentityScope().clear();
        roomDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        scheduleDaoConfig.getIdentityScope().clear();
        taskDaoConfig.getIdentityScope().clear();
        employeeDaoConfig.getIdentityScope().clear();
        guestDaoConfig.getIdentityScope().clear();
        partnerDaoConfig.getIdentityScope().clear();
        supplierDaoConfig.getIdentityScope().clear();
        dialogDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
        bookRecordDaoConfig.getIdentityScope().clear();
        outRecordDaoConfig.getIdentityScope().clear();
    }

    public HotelDao getHotelDao() {
        return hotelDao;
    }

    public RoomTypeDao getRoomTypeDao() {
        return roomTypeDao;
    }

    public RoomDao getRoomDao() {
        return roomDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ScheduleDao getScheduleDao() {
        return scheduleDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public EmployeeDao getEmployeeDao() {
        return employeeDao;
    }

    public GuestDao getGuestDao() {
        return guestDao;
    }

    public PartnerDao getPartnerDao() {
        return partnerDao;
    }

    public SupplierDao getSupplierDao() {
        return supplierDao;
    }

    public DialogDao getDialogDao() {
        return dialogDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public BookRecordDao getBookRecordDao() {
        return bookRecordDao;
    }

    public OutRecordDao getOutRecordDao() {
        return outRecordDao;
    }

}
