package com.gj.administrator.gjerp.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.gj.administrator.gjerp.domain.Schedule;
import com.gj.administrator.gjerp.domain.Task;
import com.gj.administrator.gjerp.domain.User;

import com.gj.administrator.gjerp.domain.Employee;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EMPLOYEE".
*/
public class EmployeeDao extends AbstractDao<Employee, Long> {

    public static final String TABLENAME = "EMPLOYEE";

    /**
     * Properties of entity Employee.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Employee_type = new Property(2, String.class, "employee_type", false, "EMPLOYEE_TYPE");
        public final static Property Telphone = new Property(3, String.class, "telphone", false, "TELPHONE");
        public final static Property Email = new Property(4, String.class, "email", false, "EMAIL");
        public final static Property Create_time = new Property(5, java.util.Date.class, "create_time", false, "CREATE_TIME");
        public final static Property Gender = new Property(6, String.class, "gender", false, "GENDER");
        public final static Property User_id = new Property(7, Long.class, "user_id", false, "USER_ID");
        public final static Property Task_id = new Property(8, Long.class, "task_id", false, "TASK_ID");
        public final static Property Schedule_id = new Property(9, Long.class, "schedule_id", false, "SCHEDULE_ID");
    };

    private DaoSession daoSession;

    private Query<Employee> task_EmployeesQuery;
    private Query<Employee> schedule_EmployeesQuery;

    public EmployeeDao(DaoConfig config) {
        super(config);
    }
    
    public EmployeeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EMPLOYEE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT NOT NULL ," + // 1: name
                "\"EMPLOYEE_TYPE\" TEXT NOT NULL ," + // 2: employee_type
                "\"TELPHONE\" TEXT NOT NULL ," + // 3: telphone
                "\"EMAIL\" TEXT NOT NULL ," + // 4: email
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 5: create_time
                "\"GENDER\" TEXT NOT NULL ," + // 6: gender
                "\"USER_ID\" INTEGER," + // 7: user_id
                "\"TASK_ID\" INTEGER," + // 8: task_id
                "\"SCHEDULE_ID\" INTEGER);"); // 9: schedule_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EMPLOYEE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Employee entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getEmployee_type());
        stmt.bindString(4, entity.getTelphone());
        stmt.bindString(5, entity.getEmail());
        stmt.bindLong(6, entity.getCreate_time().getTime());
        stmt.bindString(7, entity.getGender());
 
        Long user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindLong(8, user_id);
        }
 
        Long task_id = entity.getTask_id();
        if (task_id != null) {
            stmt.bindLong(9, task_id);
        }
 
        Long schedule_id = entity.getSchedule_id();
        if (schedule_id != null) {
            stmt.bindLong(10, schedule_id);
        }
    }

    @Override
    protected void attachEntity(Employee entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Employee readEntity(Cursor cursor, int offset) {
        Employee entity = new Employee( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getString(offset + 2), // employee_type
            cursor.getString(offset + 3), // telphone
            cursor.getString(offset + 4), // email
            new java.util.Date(cursor.getLong(offset + 5)), // create_time
            cursor.getString(offset + 6), // gender
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // user_id
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // task_id
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9) // schedule_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Employee entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setEmployee_type(cursor.getString(offset + 2));
        entity.setTelphone(cursor.getString(offset + 3));
        entity.setEmail(cursor.getString(offset + 4));
        entity.setCreate_time(new java.util.Date(cursor.getLong(offset + 5)));
        entity.setGender(cursor.getString(offset + 6));
        entity.setUser_id(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setTask_id(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setSchedule_id(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Employee entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Employee entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "employees" to-many relationship of Task. */
    public List<Employee> _queryTask_Employees(Long task_id) {
        synchronized (this) {
            if (task_EmployeesQuery == null) {
                QueryBuilder<Employee> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Task_id.eq(null));
                queryBuilder.orderRaw("T.'NAME' DESC");
                task_EmployeesQuery = queryBuilder.build();
            }
        }
        Query<Employee> query = task_EmployeesQuery.forCurrentThread();
        query.setParameter(0, task_id);
        return query.list();
    }

    /** Internal query to resolve the "employees" to-many relationship of Schedule. */
    public List<Employee> _querySchedule_Employees(Long schedule_id) {
        synchronized (this) {
            if (schedule_EmployeesQuery == null) {
                QueryBuilder<Employee> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Schedule_id.eq(null));
                queryBuilder.orderRaw("T.'NAME' DESC");
                schedule_EmployeesQuery = queryBuilder.build();
            }
        }
        Query<Employee> query = schedule_EmployeesQuery.forCurrentThread();
        query.setParameter(0, schedule_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getTaskDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getScheduleDao().getAllColumns());
            builder.append(" FROM EMPLOYEE T");
            builder.append(" LEFT JOIN USER T0 ON T.\"USER_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN TASK T1 ON T.\"TASK_ID\"=T1.\"_id\"");
            builder.append(" LEFT JOIN SCHEDULE T2 ON T.\"SCHEDULE_ID\"=T2.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Employee loadCurrentDeep(Cursor cursor, boolean lock) {
        Employee entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
        entity.setUser(user);
        offset += daoSession.getUserDao().getAllColumns().length;

        Task task = loadCurrentOther(daoSession.getTaskDao(), cursor, offset);
        entity.setTask(task);
        offset += daoSession.getTaskDao().getAllColumns().length;

        Schedule schedule = loadCurrentOther(daoSession.getScheduleDao(), cursor, offset);
        entity.setSchedule(schedule);

        return entity;    
    }

    public Employee loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Employee> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Employee> list = new ArrayList<Employee>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Employee> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Employee> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
