package com.gj.administrator.gjerp.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.gj.administrator.gjerp.domain.User;

import com.gj.administrator.gjerp.domain.Guest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GUEST".
*/
public class GuestDao extends AbstractDao<Guest, Long> {

    public static final String TABLENAME = "GUEST";

    /**
     * Properties of entity Guest.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Guest_type = new Property(2, int.class, "guest_type", false, "GUEST_TYPE");
        public final static Property Gender = new Property(3, String.class, "gender", false, "GENDER");
        public final static Property Telphone = new Property(4, String.class, "telphone", false, "TELPHONE");
        public final static Property Age = new Property(5, int.class, "age", false, "AGE");
        public final static Property Create_time = new Property(6, java.util.Date.class, "create_time", false, "CREATE_TIME");
        public final static Property User_id = new Property(7, Long.class, "user_id", false, "USER_ID");
        public final static Property Card_type = new Property(8, String.class, "card_type", false, "CARD_TYPE");
        public final static Property Card_id = new Property(9, String.class, "card_id", false, "CARD_ID");
        public final static Property Country = new Property(10, String.class, "country", false, "COUNTRY");
        public final static Property Address = new Property(11, String.class, "address", false, "ADDRESS");
        public final static Property Email = new Property(12, String.class, "email", false, "EMAIL");
    };

    private DaoSession daoSession;


    public GuestDao(DaoConfig config) {
        super(config);
    }
    
    public GuestDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GUEST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT NOT NULL ," + // 1: name
                "\"GUEST_TYPE\" INTEGER NOT NULL ," + // 2: guest_type
                "\"GENDER\" TEXT NOT NULL ," + // 3: gender
                "\"TELPHONE\" TEXT NOT NULL ," + // 4: telphone
                "\"AGE\" INTEGER NOT NULL ," + // 5: age
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 6: create_time
                "\"USER_ID\" INTEGER," + // 7: user_id
                "\"CARD_TYPE\" TEXT," + // 8: card_type
                "\"CARD_ID\" TEXT," + // 9: card_id
                "\"COUNTRY\" TEXT," + // 10: country
                "\"ADDRESS\" TEXT," + // 11: address
                "\"EMAIL\" TEXT);"); // 12: email
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GUEST\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Guest entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindLong(3, entity.getGuest_type());
        stmt.bindString(4, entity.getGender());
        stmt.bindString(5, entity.getTelphone());
        stmt.bindLong(6, entity.getAge());
        stmt.bindLong(7, entity.getCreate_time().getTime());
 
        Long user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindLong(8, user_id);
        }
 
        String card_type = entity.getCard_type();
        if (card_type != null) {
            stmt.bindString(9, card_type);
        }
 
        String card_id = entity.getCard_id();
        if (card_id != null) {
            stmt.bindString(10, card_id);
        }
 
        String country = entity.getCountry();
        if (country != null) {
            stmt.bindString(11, country);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(12, address);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(13, email);
        }
    }

    @Override
    protected void attachEntity(Guest entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Guest readEntity(Cursor cursor, int offset) {
        Guest entity = new Guest( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getInt(offset + 2), // guest_type
            cursor.getString(offset + 3), // gender
            cursor.getString(offset + 4), // telphone
            cursor.getInt(offset + 5), // age
            new java.util.Date(cursor.getLong(offset + 6)), // create_time
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // user_id
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // card_type
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // card_id
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // country
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // address
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // email
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Guest entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setGuest_type(cursor.getInt(offset + 2));
        entity.setGender(cursor.getString(offset + 3));
        entity.setTelphone(cursor.getString(offset + 4));
        entity.setAge(cursor.getInt(offset + 5));
        entity.setCreate_time(new java.util.Date(cursor.getLong(offset + 6)));
        entity.setUser_id(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setCard_type(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCard_id(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCountry(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setAddress(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setEmail(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Guest entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Guest entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(" FROM GUEST T");
            builder.append(" LEFT JOIN USER T0 ON T.\"USER_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Guest loadCurrentDeep(Cursor cursor, boolean lock) {
        Guest entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
        entity.setUser(user);

        return entity;    
    }

    public Guest loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Guest> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Guest> list = new ArrayList<Guest>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Guest> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Guest> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
