package com.gj.administrator.gjerp.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.gj.administrator.gjerp.domain.RoomType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ROOM_TYPE".
*/
public class RoomTypeDao extends AbstractDao<RoomType, Long> {

    public static final String TABLENAME = "ROOM_TYPE";

    /**
     * Properties of entity RoomType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Type_name = new Property(1, int.class, "type_name", false, "TYPE_NAME");
        public final static Property Bed_num = new Property(2, int.class, "bed_num", false, "BED_NUM");
        public final static Property Day_price = new Property(3, double.class, "day_price", false, "DAY_PRICE");
        public final static Property Hour_price = new Property(4, Double.class, "hour_price", false, "HOUR_PRICE");
        public final static Property Longtime_price = new Property(5, Double.class, "longtime_price", false, "LONGTIME_PRICE");
    };

    private DaoSession daoSession;


    public RoomTypeDao(DaoConfig config) {
        super(config);
    }
    
    public RoomTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ROOM_TYPE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TYPE_NAME\" INTEGER NOT NULL ," + // 1: type_name
                "\"BED_NUM\" INTEGER NOT NULL ," + // 2: bed_num
                "\"DAY_PRICE\" REAL NOT NULL ," + // 3: day_price
                "\"HOUR_PRICE\" REAL," + // 4: hour_price
                "\"LONGTIME_PRICE\" REAL);"); // 5: longtime_price
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ROOM_TYPE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RoomType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getType_name());
        stmt.bindLong(3, entity.getBed_num());
        stmt.bindDouble(4, entity.getDay_price());
 
        Double hour_price = entity.getHour_price();
        if (hour_price != null) {
            stmt.bindDouble(5, hour_price);
        }
 
        Double longtime_price = entity.getLongtime_price();
        if (longtime_price != null) {
            stmt.bindDouble(6, longtime_price);
        }
    }

    @Override
    protected void attachEntity(RoomType entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RoomType readEntity(Cursor cursor, int offset) {
        RoomType entity = new RoomType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // type_name
            cursor.getInt(offset + 2), // bed_num
            cursor.getDouble(offset + 3), // day_price
            cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4), // hour_price
            cursor.isNull(offset + 5) ? null : cursor.getDouble(offset + 5) // longtime_price
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RoomType entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType_name(cursor.getInt(offset + 1));
        entity.setBed_num(cursor.getInt(offset + 2));
        entity.setDay_price(cursor.getDouble(offset + 3));
        entity.setHour_price(cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4));
        entity.setLongtime_price(cursor.isNull(offset + 5) ? null : cursor.getDouble(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RoomType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RoomType entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
